In [1]:
from math import ceil, pi, e
from sympy import Symbol, symbols, solve, Matrix, pretty, pprint, expand, N, factor, re
from sympy.solvers.solveset import linsolve
from termcolor import colored
import numpy as np

In [2]:
def truncate(floatt,n=4):
  floatt = str(float(floatt))
  indx = floatt.find('.')
  if indx!=-1:
    try:
      return float(floatt[:indx+n+1])
    except:
      return float(floatt)
  else:
    return float(floatt)

def printt(string,color="red",end='\n'):
  print(colored(string,color),end=end)

def geturl(st):
  temp1 = str(st).replace('**','^').replace(' ','').replace('*','')    
  print(f'\n(For steps) Paste this ({temp1}) in \nhttps://www.symbolab.com/solver/simplify-calculator/simplify')

def directmethod(A):
  printt('AX = λX\nAX - λX = 0\n(A - λI)X = 0\nTo find eigen values,solve\n|A-λI| = 0')
  rows = len(A)
  A = np.array(A)
  lmbda = Symbol('λ')
  I = np.identity(rows,dtype = int)
  temp1 = Matrix(A)
  temp2 = Matrix(I)
  X = list()
  for i in range(rows):
    X.append(Symbol(f'x{i+1}'))
  symbs = X
  X = Matrix(X)

  for i in range(rows):
    if i==0:
      print(f'\n=> | {pretty(temp1.row(i))}   - λ{pretty(temp2.row(i))} | = 0')
    else:
      print(f'   | {pretty(temp1.row(i))}     {pretty(temp2.row(i))} |')

  I = lmbda*I
  temp2 = Matrix(I)

  for i in range(rows):
    if i==0:
      print(f'\n=> | {pretty(temp1.row(i))}   - {pretty(temp2.row(i))} | = 0')
    else:
      print(f'   | {pretty(temp1.row(i))}    {pretty(temp2.row(i))} |')
  
  A = A - I
  A = Matrix(A)
  for i in range(rows):
    if i==0:
      print(f'\n=> | {pretty(A.row(i))}  | = 0')
    else:
      print(f'   | {pretty(A.row(i))} |')
  
  det = A.det()
  values = solve(det)
  print(f'\n{det} = 0')
  det = expand(det)  
  print(f'{det} = 0 (Characteristic polynomial)')
  values = [truncate(re(N(val))) for val in values]
  print(f'{factor(det)} = 0')
  print(f'λ = {values}')
  geturl(det)

  for val in values:
    printt(f'\n----------------------------------\nλ = {val} (A - λI)X = 0')
    temp1 = A.subs(lmbda,val)
    for i in range(rows):
      if i==0:
        print(f'=> {pretty(temp1.row(i))}  {pretty(X.row(i))} = [0]')
      else:
        print(f'   {pretty(temp1.row(i))}  {pretty(X.row(i))}   [0]')

    dotprod = temp1.dot(X)
    varvals = [i for i in list(linsolve(dotprod,symbs))[0]]
    varvals = dict(zip(symbs,varvals))

    for i in range(rows):
      if i==0:
        print(f'\n=> [{dotprod[i]}] = [0]')
      else:
        print(f'   [{dotprod[i]}]   [0]')

    print(f"\n{dotprod[0]} = 0 {colored(f'=> {symbs[1]} = {varvals}','blue')}")
    temp1 = X.subs(varvals)
    temp2 = temp1/symbs[-1]
    flag = True
    while flag:
      for i in range(rows):
        if temp2[i]%1!=0:
          temp2*=2
          flag = True
          break
        else:
          temp2[i] = int(temp2[i])
        flag = False
        
    for i in range(rows):
      if i==0:
        print(f'[{X[i]}] = [{temp1[i]}] = [{temp2[i]}]')
      else:
        print(f'[{X[i]}]   [{temp1[i]}]   [{temp2[i]}]')

    printt(f'λ = {val}, eigen vector =')
    pprint(temp2)

In [3]:
A = [[1,1],
     [-2,4]]

directmethod(A)

AX = λX
AX - λX = 0
(A - λI)X = 0
To find eigen values,solve
|A-λI| = 0

=> | [1  1]   - λ[1  0] | = 0
   | [-2  4]     [0  1] |

=> | [1  1]   - [λ  0] | = 0
   | [-2  4]    [0  λ] |

=> | [-λ + 1  1]  | = 0
   | [-2  -λ + 4] |

(-λ + 1)*(-λ + 4) + 2 = 0
λ**2 - 5*λ + 6 = 0 (Characteristic polynomial)
(λ - 3)*(λ - 2) = 0
λ = [2.0, 3.0]

(For steps) Paste this (λ^2-5λ+6) in 
https://www.symbolab.com/solver/simplify-calculator/simplify

----------------------------------
λ = 2.0 (A - λI)X = 0
=> [-1.0  1]  [x₁] = [0]
   [-2  2.0]  [x₂]   [0]

=> [-1.0*x1 + x2] = [0]
   [-2*x1 + 2.0*x2]   [0]

-1.0*x1 + x2 = 0 => x2 = {x1: 1.0*x2, x2: x2}
[x1] = [1.0*x2] = [1]
[x2]   [x2]   [1]
λ = 2.0, eigen vector =
⎡1⎤
⎢ ⎥
⎣1⎦

----------------------------------
λ = 3.0 (A - λI)X = 0
=> [-2.0  1]  [x₁] = [0]
   [-2  1.0]  [x₂]   [0]

=> [-2.0*x1 + x2] = [0]
   [-2*x1 + 1.0*x2]   [0]

-2.0*x1 + x2 = 0 => x2 = {x1: 0.5*x2, x2: x2}
[x1] = [0.5*x2] = [1]
[x2]   [x2]   [2]
λ = 3.0, eigen vector =
⎡1⎤
⎢ ⎥
⎣2

In [4]:
A = [[8,-8,-2],
     [4,-3,-2],
     [3,-4,1]]

directmethod(A)

AX = λX
AX - λX = 0
(A - λI)X = 0
To find eigen values,solve
|A-λI| = 0

=> | [8  -8  -2]   - λ[1  0  0] | = 0
   | [4  -3  -2]     [0  1  0] |
   | [3  -4  1]     [0  0  1] |

=> | [8  -8  -2]   - [λ  0  0] | = 0
   | [4  -3  -2]    [0  λ  0] |
   | [3  -4  1]    [0  0  λ] |

=> | [-λ + 8  -8  -2]  | = 0
   | [4  -λ - 3  -2] |
   | [3  -4  -λ + 1] |

-30*λ + (-λ - 3)*(-λ + 1)*(-λ + 8) + 30 = 0
-λ**3 + 6*λ**2 - 11*λ + 6 = 0 (Characteristic polynomial)
-(λ - 3)*(λ - 2)*(λ - 1) = 0
λ = [1.0, 2.0, 3.0]

(For steps) Paste this (-λ^3+6λ^2-11λ+6) in 
https://www.symbolab.com/solver/simplify-calculator/simplify

----------------------------------
λ = 1.0 (A - λI)X = 0
=> [7.0  -8  -2]  [x₁] = [0]
   [4  -4.0  -2]  [x₂]   [0]
   [3  -4  0]  [x₃]   [0]

=> [7.0*x1 - 8*x2 - 2*x3] = [0]
   [4*x1 - 4.0*x2 - 2*x3]   [0]
   [3*x1 - 4*x2]   [0]

7.0*x1 - 8*x2 - 2*x3 = 0 => x2 = {x1: 2.0*x3, x2: 1.5*x3, x3: x3}
[x1] = [2.0*x3] = [4]
[x2]   [1.5*x3]   [3]
[x3]   [x3]   [2]
λ = 1.0, eigen vector =
⎡4⎤
⎢