In [1]:
from math import ceil, pi, e
from termcolor import colored
import numpy as np

In [2]:
def checkint(floatt):
  floatt = float(floatt)
  if floatt%1!=0:
    return floatt
  else:
    return int(floatt)

def truncate(floatt,n):
  floatt = str(float(floatt))
  indx = floatt.find('.')
  if indx!=-1:
    try:
      return checkint(floatt[:indx+n+1])
    except:
      return checkint(floatt)
  else:
    return checkint(floatt)

def printt(string,color="red",end='\n'):
  print(colored(string,color),end=end)

In [3]:
def finderror(lmbdas,k,n):
  a1, a2 = lmbdas[k-1], lmbdas[k]
  error = truncate(abs((a2-a1)/a2),n)
  print(f'Error = | ({a2} - {a1})/{a2} | => {error}\n')
  return error

def powermethod(A,x0,errorlim,n,numiters):
  flag = errorlim !=None
  rows = len(A)
  A, x0 = np.array(A), np.array(x0)
  xlist = [0,x0]
  lmbdas = [0]
  for k in range(1,numiters+1):
    printt(f'Ax{k-1}')
    dot = A.dot(xlist[k])
    dot = [truncate(i,n) for i in dot]
    lmbdas.append(max(dot, key=abs))
    dotdiv = np.divide(dot,lmbdas[k])
    dotdiv = [truncate(i,n) for i in dotdiv]
    for i in range(rows):
      if i==0:
        print(f'Ax{k-1} => {A[i]}[{xlist[k][i]}] = [{dot[i]}] = {lmbdas[k]}[{dotdiv[i]}]')
      else:
        print(f'       {A[i]}[{xlist[k][i]}]     [{dot[i]}]     [{dotdiv[i]}]')
    xlist.append(dotdiv)
    printt(f'x{k} = {dotdiv}t, λ{k} = {lmbdas[k]}',color='blue')
    error = finderror(lmbdas,k,n)
    if flag:
      if error<errorlim:
        break
  
  printt(f'{lmbdas[-1]} is the largest eigen value with eigen vector {xlist[-1]}t with error {error}','green')



In [7]:
A = [[1,2],         # matrix A
     [3,2]]

x0 = [1,1]            # initial x0
errorlim = 5/100       # if errorlim, else set to None
n = 4                 # for truncation (n decimal places)
numiters = 50          # num of iterations (set to 50 if to find using errorlim)

powermethod(A,x0,errorlim,n,numiters)

Ax0
Ax0 => [1 2][1] = [3] = 5[0.6]
       [3 2][1]     [5]     [1]
x1 = [0.6, 1]t, λ1 = 5
Error = | (5 - 0)/5 | => 1

Ax1
Ax1 => [1 2][0.6] = [2.6] = 3.8[0.6842]
       [3 2][1]     [3.8]     [1]
x2 = [0.6842, 1]t, λ2 = 3.8
Error = | (3.8 - 5)/3.8 | => 0.3157

Ax2
Ax2 => [1 2][0.6842] = [2.6842] = 4.0526[0.6623]
       [3 2][1]     [4.0526]     [1]
x3 = [0.6623, 1]t, λ3 = 4.0526
Error = | (4.0526 - 3.8)/4.0526 | => 0.0623

Ax3
Ax3 => [1 2][0.6623] = [2.6623] = 3.9869[0.6677]
       [3 2][1]     [3.9869]     [1]
x4 = [0.6677, 1]t, λ4 = 3.9869
Error = | (3.9869 - 4.0526)/3.9869 | => 0.0164

3.9869 is the largest eigen value with eigen vector [0.6677, 1]t with error 0.0164


In [5]:
A = [[1,1,0,0],         # matrix A
     [1,2,0,1],
     [0,0,3,3],
     [0,1,3,2]]

x0 = [1,1,0,1]          # initial x0
errorlim = None         # if errorlim, else set to None
n = 4                  # for truncation (n decimal places)
numiters = 3            # num of iterations (set to 50 if to find using errorlim)

powermethod(A,x0,errorlim,n,numiters)

Ax0
Ax0 => [1 1 0 0][1] = [2] = 4[0.5]
       [1 2 0 1][1]     [4]     [1]
       [0 0 3 3][0]     [3]     [0.75]
       [0 1 3 2][1]     [3]     [0.75]
x1 = [0.5, 1, 0.75, 0.75]t, λ1 = 4
Error = | (4 - 0)/4 | => 1

Ax1
Ax1 => [1 1 0 0][0.5] = [1.5] = 4.75[0.3157]
       [1 2 0 1][1]     [3.25]     [0.6842]
       [0 0 3 3][0.75]     [4.5]     [0.9473]
       [0 1 3 2][0.75]     [4.75]     [1]
x2 = [0.3157, 0.6842, 0.9473, 1]t, λ2 = 4.75
Error = | (4.75 - 4)/4.75 | => 0.1578

Ax2
Ax2 => [1 1 0 0][0.3157] = [0.9999] = 5.8419[0.1711]
       [1 2 0 1][0.6842]     [2.6841]     [0.4594]
       [0 0 3 3][0.9473]     [5.8419]     [1]
       [0 1 3 2][1]     [5.5261]     [0.9459]
x3 = [0.1711, 0.4594, 1, 0.9459]t, λ3 = 5.8419
Error = | (5.8419 - 4.75)/5.8419 | => 0.1869

5.8419 is the largest eigen value with eigen vector [0.1711, 0.4594, 1, 0.9459]t with error 0.1869


ESE

In [6]:
A = [[1,2],         # matrix A
     [3,2]]

x0 = [1,1]          # initial x0
errorlim = 0.05         # if errorlim, else set to None
n = 4                  # for truncation (n decimal places)
numiters = 50            # num of iterations (set to 50 if to find using errorlim)

powermethod(A,x0,errorlim,n,numiters)

Ax0
Ax0 => [1 2][1] = [3] = 5[0.6]
       [3 2][1]     [5]     [1]
x1 = [0.6, 1]t, λ1 = 5
Error = | (5 - 0)/5 | => 1

Ax1
Ax1 => [1 2][0.6] = [2.6] = 3.8[0.6842]
       [3 2][1]     [3.8]     [1]
x2 = [0.6842, 1]t, λ2 = 3.8
Error = | (3.8 - 5)/3.8 | => 0.3157

Ax2
Ax2 => [1 2][0.6842] = [2.6842] = 4.0526[0.6623]
       [3 2][1]     [4.0526]     [1]
x3 = [0.6623, 1]t, λ3 = 4.0526
Error = | (4.0526 - 3.8)/4.0526 | => 0.0623

Ax3
Ax3 => [1 2][0.6623] = [2.6623] = 3.9869[0.6677]
       [3 2][1]     [3.9869]     [1]
x4 = [0.6677, 1]t, λ4 = 3.9869
Error = | (3.9869 - 4.0526)/3.9869 | => 0.0164

3.9869 is the largest eigen value with eigen vector [0.6677, 1]t with error 0.0164
